production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: anagrams_development
  pool: 5
  host: localhost
  username: postgres
  password: BrAnDoN9991
    
test:
  adapter: postgresql
  database: anagrams_test
  pool: 5
  host: localhost
  username: postgres
  password: BrAnDoN9991